# Generated by Django 2.0.8 on 2018-09-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=128)),
                ('ejercicio', models.IntegerField(blank=True, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('aplicado', models.BooleanField()),
                ('validado', models.BooleanField()),
                ('bloqueado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ComedorDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.IntegerField(blank=True, null=True)),
                ('codigo_empleado', models.CharField(max_length=128)),
                ('nombre_empleado', models.CharField(max_length=128)),
                ('depto_empleado', models.CharField(max_length=128)),
                ('lunes', models.IntegerField(blank=True, null=True)),
                ('martes', models.IntegerField(blank=True, null=True)),
                ('miercoles', models.IntegerField(blank=True, null=True)),
                ('jueves', models.IntegerField(blank=True, null=True)),
                ('viernes', models.IntegerField(blank=True, null=True)),
                ('sabado', models.IntegerField(blank=True, null=True)),
                ('domingo', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('id_comedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='comedor_app.Comedor')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=128)),
                ('ejercicio', models.IntegerField(blank=True, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('dia', models.CharField(max_length=10)),
                ('comida', models.TextField(null=True)),
                ('id_comedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comedor_app.Comedor')),
                ('id_comedor_detalle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comedor_app.ComedorDetalle')),
            ],
        ),
    ]
