# Generated by Django 2.0.8 on 2018-09-07 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserAppPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=128)),
                ('value', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='UserMenuPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=128)),
                ('value', models.CharField(blank=True, max_length=6)),
                ('user_app_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_menus', to='usuarios_app.UserAppPermit')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opc_recientes', models.BooleanField(default=False)),
                ('opc_notificaciones', models.BooleanField(default=False)),
                ('indicadores', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userapppermit',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_apps', to='usuarios_app.UserProfileInfo'),
        ),
        migrations.AddField(
            model_name='empresareporte',
            name='user_company_permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_companies', to='usuarios_app.UserProfileInfo'),
        ),
    ]
